Fixing ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -82,6 +82,13 @@ jobs:
             --exclude security \
             tests/03_db
 
+      - name: Debug DB
+        run: |
+          echo "DB_PATH=$DB_PATH"
+          test -f "$DB_PATH" && echo "DB exists" || echo "DB missing"
+        env:
+          DB_PATH: ${{ github.workspace }}/juice-shop-db/juiceshop.sqlite
+
       - name: Generate Allure report
         run: |
           allure generate reports/allure/allure-results --clean -o reports/allure/allure-report
